import { Chivo } from "next/font/google";
import Menu from "@components/structure/Menu/Menu";
import SmoothScroll from "@components/structure/SmoothScroll/SmoothScroll";
import "../styles/globals.scss";
import "lenis/dist/lenis.css";



const chivo = Chivo({
  variable: "--font-chivo",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={chivo.variable}>
        <SmoothScroll>
          <Menu />
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
